<meta charset=utf-8>
<h1>Новая поставка</h1>
<div>
    <form action="/create/part" method="post">
        <input type="text" placeholder="Название детали" name="PartName"><br>
        <input type="text" placeholder="Тип детали" name="PartType"><br>

        <label for="Count">Сколько поставили</label>
        <input type="number" min=1 name="Count"><br>

        <label for="ShipmentDate">Когда поставили</label>
        <input type="datetime-local" id="shipment-date" name="ShipmentDate"><br>

        <label for="Supported">Введите принтеры, для которых подходит данная деталь</label><br>

        <input type="hidden" name="Supported" id="Supported"
            value="[
                {&quot;Model&quot;:&quot;EPSON&quot;, &quot;Original&quot;:&quot;true&quot;},
                {&quot;Model&quot;:&quot;CANON&quot;, &quot;Original&quot;:&quot;false&quot;},
                ]"><br>

        <input type="Submit">
    </form>
</div>